# If you don't set these, they will be inferred from the repo's description on GitHub.
title: Tacent
description: Tacent is a C++ library designed to be the foundation for a game pipeline or other interactive project. It implements support for linear algebra, text and file IO, UTF-N conversions, containers, image loading/saving, image quantization/filtering, command-line parsing, etc. Modern CMake (target-based) is used to generate the build files. Generators for makefiles, ninja, NMake, and Visual Studio solutions have been tested. Tacent may be compiled with gcc, clang, or msvc.
show_downloads: true
theme: jekyll-theme-minimal
